### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wzpan** [dahakawang/scu_thesis_template#1]
Hello，
试了一下你的模板，做的挺不错，有几个建议：
1. 用MikTeX编译的时候提示\textcolor没定义，加入xcolor宏包可以解决；
2. 将正文的部分和格式的部分分开。可以单独创建一个data文件夹，把正文的tex文档放在该文件夹；
3. 将格式的定制改成cls宏包或者sty样式文件，以和正文进一步分开；
4. 加入参考文献；
5. 没有Makefile？;-)

**Comment by dahakawang** [comment]
hey @wzpan 
1. 这个模板使用OS X下的LaTeX发行版，并且使用xelatex命令编译。windows下曾今使用CTEX编译成功过没有问题，你可以试试这个版本。
2. 3. 实际上你的方案3.是比2.更好的解决方案，不过对我来说毕业设计提交在即，而这个项目只是个rough solution，所以我并没有时间和精力去将其打包为sty，如果你不是很急使用这个模板，并且有意愿改善它的话，欢迎你fork我的repo然后contribute。 :smiley: 
4. 参考文献具体见任何一个LaTeX教程里的说明（推荐你了解BibTeX）
5. 我写了两个脚本的initial implementation（make.sh 和make.bat）分别对应OS X/Linux以及win下使用。不过这两个脚本主要是满足我的日常工作，确实非常ugly，同样也欢迎你contribute。
